version: '3.5'

networks:
  solace_msg_net:
    name: solace_msg_net
    external: false
    driver: bridge

services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    command: ["--memory.max-traces=1000"]
    networks:
      - solace_msg_net
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
      - "14268:14268"
      - "14250:14250"
  


  solbroker:
    image: $PUBSUB_IMAGE
    hostname: $PUBSUB_HOSTNAME
    networks:
      - solace_msg_net
    env_file:
      - ./solace_config_keys.env

    ports:
      - "2222:2222"
      - "8080:8080"
      - "55443:55443"
      - "55445:55445"
      - "${PUBSUB_PORT_NUMBER}:55555"
      - "55556:55556"
      - "5671:5671"
      - "5672:5672"
      - "5550:5550"
      - "1943:1943"
      - "8008:8008"
    shm_size: 2g
    ulimits:
      memlock: -1
      nofile:
        soft: 2448
        hard: 42192
