version: '3.5'

networks:
  solace_msg_net:
    name: solace_msg_net
    external: false
    driver: bridge

services:
  
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    networks:
      - solace_msg_net
    ports:
      - 8000:8000
      - 8088:8088
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=admin123
