processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 500
  batch: null
exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  splunk_hec:
    endpoint: http://10.0.0.229:8088/services/collector/event
    token: ba690277-a3d4-46c9-a268-c186750bb59b
    tls:
      insecure: true
receivers:
  otlp:
    protocols:
      grpc: null
  solace:
    broker:
      - solbroker:5672
    max_unacknowledged: 500
    auth:
      sasl_plain:
        username: trace
        password: trace
    queue: queue://#telemetry-default
    tls:
      insecure: true
      insecure_skip_verify: true
service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers:
        - solace
        - otlp
      processors:
        - batch
        - memory_limiter
      exporters:
        - jaeger
        - logging
        - splunk_hec



  



